### ISSUE TITLE
Handing over texture packs

### ISSUE THREAD

**Issue by VanessaE** [minetest-texture-packs/minetest-texture-packs.github.io#1]
Just putting this out there -- in my "move my mods" thread on mt-mods (https://github.com/mt-mods/mt-mods/issues/1), this group was recommended to take over maintenance of my texture packs.  I'm happy with that idea.  See that link for a list.

@tacotexmex ping again :wink:

**Comment by wsor4035** [comment]
@Panquesito7 ping as you commented in that thread

**Comment by tacotexmex** [comment]
How are these TPs wrt quality and coherence?

**Comment by VanessaE** [comment]
Well I would like to believe they're top-of-the-line.  *I* made them, after all. :grin:
